- .buildkite/pipeline.yaml
This lets me experiment with buildkite agent configuration.
There are some limitations currently, including:
* No caching 
* ~~Fixed build environment (`rust:1.36.0-slim-buster` doge image)~~
* No buildkite plugins or hooks
* No build for 3rd party pull requests
Some of these will be possible in the future, others not because security.
> Experimental: buildkite CI

- Cargo.lock
- Cargo.toml
- bin/adjacency_matrix.rs
Context: we started implementing the "naive" pagerank algorithm because it was very easy to implement. This algorithm requires inverting a matrix and the way to do this in `ndarray` is by using the `ndarray_linalg` crate which piggybacks on Lapack & OpenBlas. These two requires external libraries to be provisioned, for @kim 's joy.
However, this algorithm was flawed: for big matrixes was yielding negative pageranks, and we later transitioned to an iterative (and equally simple) version that doesn't require matrix inversion.
This PR kills the `pagerank_naive` algorithm and all the library baggage associated with it.
> Kill the naive pagerank algo

- .buildkite/pipeline.yaml
- docker/build/Dockerfile
Built dependencies (and possibly other stuff) is now cached per-build-agent via [sccache](https://github.com/mozilla/sccache).
Note that we don't currently support building docker images on CI. Should the need for linear algebra re-arise at a later point (or other toolchain customisations, such as the rustc wasm target), please build the image locally and push it to the goog registry.
> CI: Custom docker image with sccache

- src/algorithm.rs
This fixes 2 problems:
- `total_walks` already includes all walks for all nodes (ie `nR`) so it shouldn't be multiplied again by the number of vertices
- I believe there is an error in the oscoin white paper. It defines `1 − ε_project` as the probability that the random walks terminates (this also goes along with some definitions of damping factors). The paper from which the rank formula is taken ([incremental PageRank](http://snap.stanford.edu/class/cs224w-readings/bahmani10pagerank.pdf)), defines it the other way around though, so that the resulting formula should be `W_x * (1 - ε_project) / nR` instead of `W_x * ε_project / nR`.
> Fix rank_network implementation

- docker/build/Dockerfile
This will persist the crates.io index and any source dependencies across builds.
Also allows mounting the rootfs read-only.
> CI: Put CARGO_HOME on /cache volume

- Cargo.lock
- Cargo.toml
- bin/adjacency_matrix.rs
- bin/main.rs
- bin/source_contributions.rs
- src/adjacency.rs
- src/algorithm.rs
- src/importers/csv.rs
- src/importers/gephi_json.rs
- src/importers/mod.rs
- src/lib.rs
- src/linalg.rs
- src/protocol_traits/graph.rs
- src/protocol_traits/ledger.rs
- src/types.rs
This PR completely overhauls the `Graph` protocol trait (as well as `types.rs`) and makes it closer to the vision described by @cloudhead (which might be interested to also review this work).
I am sure this won't be the _last_ time we modify these traits, but now I think it's definitely better than it was before. The motivation for this huge refactoring was the CSV importer. While writing it, I did realise our Graph API was very weak and didn't allow effective query over the graph. Now, thanks to the new trait and the CSV importer, we can do:
```rust
let network: Network<f64> = super::import_network(
csv::ReaderBuilder::new()
.flexible(true)
.from_reader(deps_file),
csv::ReaderBuilder::new()
.flexible(true)
.from_reader(meta_file),
csv::ReaderBuilder::new()
.flexible(true) …
```
> CSV Importer

- Cargo.lock
- Cargo.toml
- src/algorithm.rs
- src/importers/csv.rs
This PR abstracts away the `thread_rng` from the algorithm making it seed & RNG agnostic.
> Sketch of the generic seed API

- bin/adjacency_matrix.rs
- src/importers/csv.rs
Fixes #18. We now use a `std::rc::Rc` in `csv.rs` to avoid an extra bunch of expensive `.clone()`.
> Avoid extra clones in csv.rs

- src/importers/csv.rs
This PR adds a (runnable, but ignored) doc-test to the `import_network` function to demonstrate its usage. Merle, if you copy & paste this into your benchmark code, it should "just work(TM)" 😁
> Document csv importer better

- src/algorithm.rs
- src/types.rs
This PR fixes the compilation errors by banging `Clone` everywhere 💔 .
This will be eventually fixed by the `GraphView` / `NetworkView` abstraction, which will be very cheap to clone/copy, but for now this should do.
We should nevertheless open a tech debt ticket to remove all these extra instances of `Clone`, as it shouldn't be possible (imho) to clone a graph, the users should be using the `GraphAPI` functions to get `GraphView` s out of a graph.
**Note:** This PR is opened against the base branch `mb/seed-set`, which means we would need to first merge this one, rebase `mb/seed-set` against master and finally merge everything.
> Clone galore

- .buildkite/pipeline.yaml
This PR aims to add a new step to CI, so that we build (but don't run) benchmarks, so that we can catch build regressions (it happens to me twice, already!).
> Add new CI step for bench

- benches/osrank_naive.rs
- bin/main.rs
- bin/source_contributions.rs
- bin/source_dependencies.rs
- src/algorithm.rs
- src/protocol_traits/graph.rs
- src/types/network.rs
- src/types/walk.rs
This quick PR fixes a number of compilation warnings (and `cargo clippy` lints) which appeared after I did upgrade my `rustc` compiler to `1.37`.
> Fix Rust 1.37 warnings

- .buildkite/coverage.yaml
- .buildkite/pipeline.yaml
- codecov.yml
- docker/build/Dockerfile
This PR merges the two rust-specific `RUST` in the `Dockerfile`, although this didn't come with a less beefy image. I did try to use `docker build --squash` and also the now-seemingly-broken tool `docker-squash`, but couldn't do better than 1.74GB, oh well.
I have also switched to be using the newly-pushed Docker image as identified by its SHA, to have precise control over it.
> Use a Docker image specified by its SHA

- src/types/mock.rs
This PR fixes a small grammar typo that @MeBrei noticed in my work on #41 but that I did forget to fix previously.
> Fix spell typo

- src/protocol_traits/graph.rs
- src/types/mock.rs
- src/types/network.rs
This PR adds a bunch of traits which wraps some confusingly-named `petgraph` methods, so that it gets less confusing to use petgraph in circumstances where the term `weight` is fairly overloaded (as it's also a concept introduced by `osrank` and the `oscoin-graph-api`.
> Add traits to improve API readability

- README.md
Fixes #36.
As per our discussion, the README now includes an (external) link to the (private for now) osrank specification. There is no real reason for the specification to be private, it's just that in the current docs organisation, it lives inside a private repository.
> Bump the README

- Cargo.lock
- Cargo.toml
- benches/osrank_naive.rs
- src/algorithm.rs
- src/types/mock.rs
- src/types/network.rs
This patch switches the `algorithm.rs` module to use the `GraphAlgorithm` trait from `oscoin-graph-api`.
> Refactor algorithm.rs and switch to the GraphAlgorithm trait

- Cargo.lock
- Cargo.toml
- src/algorithm.rs
- src/lib.rs
Fixes #61.
This PR adds arguably the most important test of the testsuite: it tests (via quickcheck) that given a random graph and a random initial seed, if we run the osrank algorithm on the same (cloned) graph and the same seed twice, the results matches, i.e. given a fixed seed, the algorithm is deterministic.
> Add test for deterministic osrank

- Cargo.lock
- Cargo.toml
- benches/osrank_naive_development.rs
- src/algorithm.rs
- src/benchmarks/util.rs
- src/protocol_traits/graph.rs
- src/types/mock.rs
This PR ports the code to use the new `GraphAnnotator` abstraction.
It's marked as draft as it relies on the unreleased new version of `graph-api`.
> Port the code to use the GraphAnnotator

- Cargo.lock
- Cargo.toml
- bin/adjacency_matrix.rs
- bin/export_gephi.rs
- src/exporters/gexf.rs
- src/exporters/graphml.rs
- src/exporters/mod.rs
- src/importers/csv.rs
This is the first iteration for #51.
While the exporter technically work, it its current state is not very useful as the generate graph is huge, and it's the "un-normalised" one. One might argue this is orthogonal to the exporter itself, and I'd agree with that.
Another thing which is not possible to do is to give nodes space coordinates, so usually once the `.gexf` is exported is necessary to open it with an external tool (like the Gephi's Desktop app) and force a layout (e.g. Atlas). Last but not least, at the moment the label for each node is simply "test" and there are no weights on the edges and no `osrank` property for nodes.
> Gexf exporter

- Cargo.lock
- Cargo.toml
- benches/osrank_naive_development.rs
- benches/osrank_naive_nightly.rs
- bin/export_gephi.rs
- src/algorithm.rs
- src/benchmarks/util.rs
- src/exporters/graphml.rs
- src/types/walk.rs
Fixed #71. There were a bunch of modifications I had to do in order to parallelise this:
1. Now we need to clone the `RNG` before passing it to each separate "thread" (it's not really a thread as we are using `rayon` under the hood so a thread pool is (re)used); this means that now the choice of _which_ `RNG` we use is essential for the algorithm to behave correctly. More specifically, we are now dropping the use of `XorShiftRng` due a cloning [pitfall](https://rust-random.github.io/rand/rand/trait.SeedableRng.html#method.from_rng) and we are using the `Xoshiro256StarStar` which is of higher quality and actually faster (7 Gb/s according to the "Rust rand book" vs 5 Gb/s);
2. After profiling the code, I did realise we had another bottleneck  (that @MeBrei warned me about for a while): our …
> Have a go at parallelising the osrank naive algorithm

- benches/osrank_naive_development.rs
- bin/export_gephi.rs
- src/algorithm/mod.rs
- src/algorithm/naive.rs
- src/benchmarks/util.rs
- src/importers/csv.rs
This PR fixes #66, by creating a `Normalised` newtype wrapper over a `Graph` plus a companion [sealed](https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html) `NormalisedGraph` trait to be used to prevent different `GraphAlgorithm` implementations to use the wrong "shape" for a `Graph`. More specifically, the "naive" algorithm assumes and requires the graph to be "normalised", i.e. a graph where each pair of nodes `(N1,N2)` has at most one outgoing edges from `N1` to `N2`, which is computed via some matrix arithmetic.
However, the montecarlo incremental algorithm relax this constraint and it's actually necessary for a graph to allow multiple edges, so that weight can be calculated on the fly. This means it would be a mistake trying to call one or the other algorithm with …
> Fix #66 (Add Normalised & NormalisedGraph)

- bin/export_gephi.rs
- src/exporters/gexf.rs
- src/exporters/graphml.rs
- src/exporters/mod.rs
This PR makes the `exporters::gexf` module capable of rendering extra information relative to size, color & osrank, in the same way `graphml` does. Now the two exporters are "features-par".
> Support size, rank & colors in Gexf exporter

- Cargo.toml
- bin/adjacency_matrix.rs
- bin/export_gephi.rs
- bin/rank.rs
- src/algorithm/incremental.rs
- src/algorithm/mod.rs
- src/exporters/csv.rs
- src/exporters/gexf.rs
- src/exporters/graphml.rs
- src/exporters/mod.rs
- src/types/mock.rs
- src/types/mod.rs
- src/types/walk.rs
This PR allows `osrank` to be run from the CLI and override pretty much every possible parameter, making the `osrank-rank` executable very suitable for simulations.
The only thing we cannot override is the initial RNG seed, but I don't think we will need this any time soon, and it shouldn't matter too much for the simulations.
> Allow osrank to be run via the CLI with configurable params

- .buildkite/nightly.yaml
- src/benchmarks/util.rs
Fixes #82.
We now pass the extra path to the files as 3 distinct env vars, and in the CI we download those files via cURL and pass them to the benchmark binary.
> Fix broken nightly benchmarks

- Cargo.toml
- bin/rank.rs
Fixes #88. Now `osrank-rank` can be passed an extra `--initial-seed <u64>` argument to override the initial RNG seed. For example:
```
RUST_LOG=debug ./target/release/osrank-rank \
--contribs ../osrank-rs-ecosystems/ecosystems/cargo_contributions.csv \
--deps ../osrank-rs-ecosystems/ecosystems/cargo_dependencies.csv \
--deps-meta ../osrank-rs-ecosystems/ecosystems/cargo_dependencies_meta.csv \
-o ../cargo_rank3.csv --iter 1 --initial-seed 42
```
Fixes #88 .
> Fix #88 (pass rngSeed CLI)
